name = "Beforerr"
uuid = "49aed396-608e-4c3f-b6d6-a749216c9ea7"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]
version = "0.1.0"

[deps]
AlgebraOfGraphics = "cbdf2221-f076-402e-a563-3d30da359d67"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[compat]
AlgebraOfGraphics = "0.6"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
